
// This file has been generated by the GUI designer. Do not modify.
namespace NIRSapp
{
	public partial class FileChooserWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.FileChooserWidget FileChooser;

		private global::Gtk.Button AddFileButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NIRSapp.FileChooserWindow
			this.Name = "NIRSapp.FileChooserWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Ajouter un fichier");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Container child NIRSapp.FileChooserWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.FileChooser = new global::Gtk.FileChooserWidget(((global::Gtk.FileChooserAction)(0)));
			this.FileChooser.Name = "FileChooser";
			this.FileChooser.SelectMultiple = true;
			this.vbox1.Add(this.FileChooser);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.FileChooser]));
			w1.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.AddFileButton = new global::Gtk.Button();
			this.AddFileButton.CanFocus = true;
			this.AddFileButton.Name = "AddFileButton";
			this.AddFileButton.UseUnderline = true;
			this.AddFileButton.Label = global::Mono.Unix.Catalog.GetString("Ajouter les fichiers");
			this.vbox1.Add(this.AddFileButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.AddFileButton]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(15));
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 864;
			this.DefaultHeight = 468;
			this.Show();
			this.FileChooser.SelectionChanged += new global::System.EventHandler(this.OnFileChooserSelectionChanged);
			this.AddFileButton.Clicked += new global::System.EventHandler(this.OnAddFileButtonClicked);
		}
	}
}
