
// This file has been generated by the GUI designer. Do not modify.
namespace NIRSapp
{
	public partial class ResultsWidget
	{
		private global::Gtk.Frame frame3;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox6;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label3;

		private global::Gtk.Label label5;

		private global::Gtk.Label label6;

		private global::Gtk.Label label1;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Label TsiValueLabel;

		private global::Gtk.Label HHbValueLabel;

		private global::Gtk.Label ThbValueLabel;

		private global::Gtk.Label ohbValueLabel;

		private global::Gtk.HBox hbox7;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label4;

		private global::Gtk.Label label10;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label PenteBaselineValueLabel;

		private global::Gtk.Label PenteFinValueLabel;

		private global::Gtk.Label PenteValueLabel;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.Label GtkResultsLabel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NIRSapp.ResultsWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "NIRSapp.ResultsWidget";
			// Container child NIRSapp.ResultsWidget.Gtk.Container+ContainerChild
			this.frame3 = new global::Gtk.Frame();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame3.BorderWidth = ((uint)(5));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			this.vbox4.BorderWidth = ((uint)(9));
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("ΔTSI :");
			this.vbox2.Add(this.label3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label3]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("ΔHHb :");
			this.vbox2.Add(this.label5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label5]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = "ΔtHb :";
			this.vbox2.Add(this.label6);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label6]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("ΔO2Hb : ");
			this.vbox2.Add(this.label1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label1]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.hbox6.Add(this.vbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.vbox2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.TsiValueLabel = new global::Gtk.Label();
			this.TsiValueLabel.Name = "TsiValueLabel";
			this.TsiValueLabel.Xalign = 1F;
			this.TsiValueLabel.LabelProp = global::Mono.Unix.Catalog.GetString("0");
			this.TsiValueLabel.Selectable = true;
			this.vbox5.Add(this.TsiValueLabel);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.TsiValueLabel]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.HHbValueLabel = new global::Gtk.Label();
			this.HHbValueLabel.Name = "HHbValueLabel";
			this.HHbValueLabel.Xalign = 1F;
			this.HHbValueLabel.LabelProp = global::Mono.Unix.Catalog.GetString("0");
			this.HHbValueLabel.Selectable = true;
			this.vbox5.Add(this.HHbValueLabel);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.HHbValueLabel]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.ThbValueLabel = new global::Gtk.Label();
			this.ThbValueLabel.Name = "ThbValueLabel";
			this.ThbValueLabel.Xalign = 1F;
			this.ThbValueLabel.LabelProp = global::Mono.Unix.Catalog.GetString("0");
			this.ThbValueLabel.Selectable = true;
			this.vbox5.Add(this.ThbValueLabel);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.ThbValueLabel]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.ohbValueLabel = new global::Gtk.Label();
			this.ohbValueLabel.Name = "ohbValueLabel";
			this.ohbValueLabel.Xalign = 1F;
			this.ohbValueLabel.LabelProp = global::Mono.Unix.Catalog.GetString("0");
			this.ohbValueLabel.Selectable = true;
			this.vbox5.Add(this.ohbValueLabel);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.ohbValueLabel]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			this.hbox6.Add(this.vbox5);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.vbox5]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox4.Add(this.hbox6);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox6]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Pente baseline :");
			this.vbox1.Add(this.label2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label2]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Pente fin :");
			this.vbox1.Add(this.label4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label4]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("ΔPente : ");
			this.vbox1.Add(this.label10);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label10]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox7.Add(this.vbox1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.vbox1]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.PenteBaselineValueLabel = new global::Gtk.Label();
			this.PenteBaselineValueLabel.Name = "PenteBaselineValueLabel";
			this.PenteBaselineValueLabel.Xalign = 0F;
			this.PenteBaselineValueLabel.LabelProp = global::Mono.Unix.Catalog.GetString("0");
			this.PenteBaselineValueLabel.Selectable = true;
			this.vbox3.Add(this.PenteBaselineValueLabel);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.PenteBaselineValueLabel]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.PenteFinValueLabel = new global::Gtk.Label();
			this.PenteFinValueLabel.Name = "PenteFinValueLabel";
			this.PenteFinValueLabel.Xalign = 0F;
			this.PenteFinValueLabel.LabelProp = global::Mono.Unix.Catalog.GetString("0");
			this.PenteFinValueLabel.Selectable = true;
			this.vbox3.Add(this.PenteFinValueLabel);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.PenteFinValueLabel]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.PenteValueLabel = new global::Gtk.Label();
			this.PenteValueLabel.Name = "PenteValueLabel";
			this.PenteValueLabel.Xalign = 0F;
			this.PenteValueLabel.LabelProp = global::Mono.Unix.Catalog.GetString("0");
			this.PenteValueLabel.Selectable = true;
			this.vbox3.Add(this.PenteValueLabel);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.PenteValueLabel]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox7.Add(this.vbox3);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.vbox3]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			w19.Padding = ((uint)(5));
			this.vbox4.Add(this.hbox7);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox7]));
			w20.PackType = ((global::Gtk.PackType)(1));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vbox4.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator1]));
			w21.PackType = ((global::Gtk.PackType)(1));
			w21.Position = 2;
			w21.Fill = false;
			w21.Padding = ((uint)(10));
			this.GtkAlignment.Add(this.vbox4);
			this.frame3.Add(this.GtkAlignment);
			this.GtkResultsLabel = new global::Gtk.Label();
			this.GtkResultsLabel.Name = "GtkResultsLabel";
			this.GtkResultsLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>ResultWidget</b>");
			this.GtkResultsLabel.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkResultsLabel;
			this.Add(this.frame3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
